# Generated by Django 4.2.7 on 2025-08-26 20:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', verbose_name='Контент'),
        ),
    ]
