# Generated by Django 4.2.7 on 2025-08-26 20:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='description',
            field=tinymce.models.HTMLField(default='<p>Описание</p>', verbose_name='Описание'),
        ),
    ]
