# Generated by Django 4.2.7 on 2025-08-26 21:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newscategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='content',
            field=tinymce.models.HTMLField(default='<p>Описание</p>', verbose_name='Описание на странице'),
        ),
    ]
