# Generated by Django 4.2.7 on 2025-08-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_newscategory_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscategory",
            name="meta_keywords",
            field=models.CharField(
                default=" ", max_length=200, verbose_name="Ключевые слова"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newscategory",
            name="meta_title",
            field=models.CharField(
                default=" ", max_length=200, verbose_name="Мета заголовок"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
