# Generated by Django 5.2.9 on 2026-01-02 13:43

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_image_alter_newscategory_header_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем.', max_length=200, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='header_description',
            field=models.TextField(blank=True, help_text='Дополнительный текст под заголовком.', null=True, verbose_name='Описание шапки'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Фоновое изображение для заголовка страницы.', null=True, upload_to=main.utils.RenameUploadTo('headers/'), verbose_name='Изображение шапки'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='header_title',
            field=models.CharField(blank=True, help_text='Оставьте пустым для использования стандартного названия.', max_length=200, null=True, verbose_name='Заголовок шапки'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем.', max_length=200, verbose_name='Мета заголовок'),
        ),
    ]
