# Generated by Django 5.2.9 on 2026-01-06 00:26

import django.db.models.deletion
import main.utils
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_options_news_news_date_alter_news_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('event_type', models.CharField(choices=[('portfolio_added', 'Добавлена работа в портфолио'), ('portfolio_updated', 'Обновлена работа в портфолио'), ('review_approved', 'Одобрен отзыв'), ('page_created', 'Создана страница'), ('page_updated', 'Обновлена страница'), ('service_added', 'Добавлена услуга'), ('service_updated', 'Обновлена услуга'), ('other', 'Другое событие')], max_length=50, verbose_name='Тип события')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок события')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание события')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип связанного объекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.utils.RenameUploadTo('news/events/'), verbose_name='Изображение события')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='news.news', verbose_name='Новость дня')),
            ],
            options={
                'verbose_name': 'Событие дня',
                'verbose_name_plural': 'События дня',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
