# Generated by Django 5.2.9 on 2026-01-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_dailyevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyevent',
            name='event_type',
            field=models.CharField(choices=[('portfolio_added', 'Добавлена работа в портфолио'), ('portfolio_updated', 'Обновлена работа в портфолио'), ('review_approved', 'Одобрен отзыв'), ('page_created', 'Создана страница'), ('page_updated', 'Обновлена страница'), ('service_added', 'Добавлена услуга'), ('service_updated', 'Обновлена услуга'), ('service_order_new', 'Новый заказ услуги'), ('other', 'Другое событие')], max_length=50, verbose_name='Тип события'),
        ),
    ]
