# Generated by Django 5.2.9 on 2026-03-09 23:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_dailyevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyevent',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание события'),
        ),
        migrations.AddField(
            model_name='dailyevent',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание события'),
        ),
        migrations.AddField(
            model_name='dailyevent',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок события'),
        ),
        migrations.AddField(
            model_name='dailyevent',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок события'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='content_en',
            field=tinymce.models.HTMLField(default='<p>Описание</p>', null=True, verbose_name='Описание на странице'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='content_ru',
            field=tinymce.models.HTMLField(default='<p>Описание</p>', null=True, verbose_name='Описание на странице'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
