# Generated by Django 5.2.9 on 2026-03-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_dailyevent_description_en_dailyevent_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyevent',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='dailyevent',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='dailyevent',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='dailyevent',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='name_ru',
        ),
    ]
