# Generated by Django 5.2.9 on 2026-08-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_dailyevent_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyevent',
            name='event_type',
            field=models.CharField(choices=[('portfolio_added', 'Добавлена работа в портфолио'), ('portfolio_updated', 'Обновлена работа в портфолио'), ('review_approved', 'Одобрен отзыв'), ('page_created', 'Создана страница'), ('page_updated', 'Обновлена страница'), ('service_added', 'Добавлена услуга'), ('service_updated', 'Обновлена услуга'), ('service_order_new', 'Новый заказ услуги'), ('price_plan_added', 'Добавлен тарифный план'), ('price_plan_updated', 'Обновлён тарифный план'), ('other', 'Другое событие')], max_length=50, verbose_name='Тип события'),
        ),
    ]
