# Generated by Django 5.2.9 on 2026-01-04 21:17

import django.db.models.deletion
import main.utils
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем.', max_length=200, verbose_name='Мета заголовок')),
                ('meta_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, verbose_name='Ключевые слова')),
                ('meta_description', models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, verbose_name='Мета описание')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.FileField(blank=True, null=True, upload_to=main.utils.RenameUploadTo('services/icons/'), verbose_name='Иконка (SVG/PNG)')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', tinymce.models.HTMLField(default='<p>Описание услуги</p>', verbose_name='Полное описание')),
                ('technical_requirements', tinymce.models.HTMLField(blank=True, help_text='Языки, особенности и т.д.', verbose_name='Технические условия')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('range', 'От и До')], default='fixed', max_length=10, verbose_name='Тип цены')),
                ('price_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фиксированная цена')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена ОТ')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена ДО')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ услуги',
                'verbose_name_plural': 'Заказы услуг',
                'ordering': ['-created_at'],
            },
        ),
    ]
