# Generated by Django 5.2.9 on 2026-01-06 19:57

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=main.utils.RenameUploadTo('services/icons/'), verbose_name='Иконка (JPG/GIF/PNG)'),
        ),
    ]
