# Generated by Django 5.2.9 on 2026-01-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='technical_requirements',
            field=models.CharField(blank=True, help_text='Языки, особенности и т.д.', max_length=255, verbose_name='Технические условия'),
        ),
    ]
