# Generated by Django 5.2.9 on 2026-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_technical_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='technical_requirements',
            field=models.TextField(blank=True, help_text='Выбранные значения сохраняются через запятую', verbose_name='Технические условия'),
        ),
    ]
