# Generated by Django 5.2.9 on 2026-01-10 06:35

import django.db.models.deletion
import main.utils
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_technical_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='estimated_time',
            field=models.CharField(blank=True, help_text='Например: 3-5 дней, 2 недели и т.д.', max_length=100, verbose_name='Примерные сроки'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Отображать в блоке популярных услуг', verbose_name='Популярная услуга'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Внутренние заметки по заказу', verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='deadline',
            field=models.DateField(blank=True, help_text='Дата, к которой необходимо выполнить работу', null=True, verbose_name='Желаемый срок выполнения'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ориентировочная стоимость по мнению клиента', max_digits=12, null=True, verbose_name='Предварительный бюджет'),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль (₽)'), ('USD', 'Доллар ($)'), ('EUR', 'Евро (€)'), ('KZT', 'Тенге (₸)')], default='RUB', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(default='<p>Описание услуги</p>', help_text='Подробное описание услуги с возможностью форматирования', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, help_text='Рекомендуемый размер: 64x64 или 128x128 пикселей', null=True, upload_to=main.utils.RenameUploadTo('services/icons/'), verbose_name='Иконка (JPG/GIF/PNG/SVG)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена в указанной валюте', max_digits=12, null=True, verbose_name='Фиксированная цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная цена диапазона', max_digits=12, null=True, verbose_name='Цена ДО'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная цена диапазона', max_digits=12, null=True, verbose_name='Цена ОТ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('range', 'От и До'), ('contact', 'По договоренности')], default='fixed', max_length=10, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Краткое описание для превью', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL', max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Максимальная длина - 200 символов', max_length=200, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='message',
            field=models.TextField(blank=True, help_text='Подробное описание того, что необходимо сделать', verbose_name='Комментарий/Задача'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='phone',
            field=models.CharField(help_text='Формат: +7XXXXXXXXXX', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('in_progress', 'В работе'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['order', 'is_active'], name='services_se_order_e13c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_popular', 'is_active'], name='services_se_is_popu_05a630_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status', 'created_at'], name='services_se_status_a7cfef_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['service', 'status'], name='services_se_service_588a04_idx'),
        ),
    ]
