# Generated by Django 5.2.9 on 2026-01-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_estimated_time_service_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='technical_requirements',
            field=models.TextField(blank=True, help_text='Перечислите технологии через запятую', verbose_name='Технические требования'),
        ),
    ]
