# Generated by Django 5.2.9 on 2026-01-10 07:16

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_technical_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, help_text='Например: Веб-разработка, Дизайн, SEO и т.д.', max_length=100, verbose_name='Категория услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='complexity_level',
            field=models.CharField(choices=[('simple', 'Простой'), ('medium', 'Средний'), ('complex', 'Сложный'), ('expert', 'Экспертный')], default='medium', max_length=50, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables',
            field=tinymce.models.HTMLField(blank=True, help_text='Список результатов/документов которые получит клиент', verbose_name='Что вы получите'),
        ),
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='services_se_categor_d8f4e5_idx'),
        ),
    ]
