# Generated by Django 5.2.9 on 2026-02-23 08:25

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_category_service_complexity_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Python, UI/UX Design, Docker, Figma', max_length=100, unique=True, verbose_name='Название технологии/инструмента')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на услугу', 'verbose_name_plural': 'Заявки на услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='technical_requirements',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, help_text='Используется для группировки услуг (напр. Веб-разработка, Дизайн и др.)', max_length=100, verbose_name='Категория (Тег)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='complexity_level',
            field=models.CharField(choices=[('simple', 'Простой'), ('medium', 'Средний'), ('complex', 'Сложный'), ('expert', 'Ультра-кодинг')], default='medium', max_length=50, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='service',
            name='deliverables',
            field=tinymce.models.HTMLField(blank=True, help_text='Результат который отправляется заказчику на руки (файлы, макеты, код)', verbose_name='Что будет в результате'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(default='<p>Описание услуги</p>', help_text='Подробное описание профиля услуги с использованием форматирования', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_time',
            field=models.CharField(blank=True, help_text="Например: '2-3 недели', 'до 5 рабочих дней'", max_length=100, verbose_name='Сроки выполнения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Вывод услуги в спец-блоках с тегом 'популярное'", verbose_name='Популярная услуга (Хит продаж)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше номер, тем выше запись в каталоге', verbose_name='Индекс сортировки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Итоговая цена (при фиксированной оплате)', max_digits=12, null=True, verbose_name='Фиксированная цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Верхняя граница диапазона', max_digits=12, null=True, verbose_name='Конечная цена (ДО)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Нижняя граница диапазона', max_digits=12, null=True, verbose_name='Начальная цена (ОТ)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('range', 'От и До'), ('contact', 'По договоренности')], default='fixed', max_length=10, verbose_name='Тип ценообразования'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Краткое описание для отображения в списках/карточках', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Для внутренней коммуникации команды', verbose_name='Служебные пометки (невидимо клиенту)'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Желательный дедлайн'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Указанный бюджет'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='message',
            field=models.TextField(blank=True, help_text='Детальное разъяснение задачи клиентом', verbose_name='Уточнения/Комментарий'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='phone',
            field=models.CharField(help_text='Примерном: +7(900)123-45-67', max_length=25, verbose_name='Номер связи'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service', verbose_name='Назначенная услуга'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('in_progress', 'Поступил в работу'), ('completed', 'Реализован/Выполнен'), ('cancelled', 'Отменен/Заморожен')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='Выберите неограниченное число технологий (веб-разработка, дизайн и др.)', related_name='services', to='services.technology', verbose_name='Стек технологий'),
        ),
    ]
