# Generated by Django 5.2.9 on 2026-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_technology_alter_serviceorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_available_for_order',
            field=models.BooleanField(default=True, help_text='Если отключено, вместо кнопки заказа будет выведено сообщение о временной недоступности', verbose_name='Доступно для заказа'),
        ),
    ]
