# Generated by Django 5.2.9 on 2026-03-09 23:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_is_available_for_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_en',
            field=models.CharField(blank=True, help_text='Используется для группировки услуг (напр. Веб-разработка, Дизайн и др.)', max_length=100, null=True, verbose_name='Категория (Тег)'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_ru',
            field=models.CharField(blank=True, help_text='Используется для группировки услуг (напр. Веб-разработка, Дизайн и др.)', max_length=100, null=True, verbose_name='Категория (Тег)'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Результат который отправляется заказчику на руки (файлы, макеты, код)', null=True, verbose_name='Что будет в результате'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_ru',
            field=tinymce.models.HTMLField(blank=True, help_text='Результат который отправляется заказчику на руки (файлы, макеты, код)', null=True, verbose_name='Что будет в результате'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=tinymce.models.HTMLField(default='<p>Описание услуги</p>', help_text='Подробное описание профиля услуги с использованием форматирования', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=tinymce.models.HTMLField(default='<p>Описание услуги</p>', help_text='Подробное описание профиля услуги с использованием форматирования', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_time_en',
            field=models.CharField(blank=True, help_text="Например: '2-3 недели', 'до 5 рабочих дней'", max_length=100, null=True, verbose_name='Сроки выполнения'),
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_time_ru',
            field=models.CharField(blank=True, help_text="Например: '2-3 недели', 'до 5 рабочих дней'", max_length=100, null=True, verbose_name='Сроки выполнения'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Краткое описание для отображения в списках/карточках', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ru',
            field=tinymce.models.HTMLField(blank=True, help_text='Краткое описание для отображения в списках/карточках', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(help_text='Максимальная длина - 200 символов', max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(help_text='Максимальная длина - 200 символов', max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_en',
            field=models.CharField(help_text='Например: Python, UI/UX Design, Docker, Figma', max_length=100, null=True, unique=True, verbose_name='Название технологии/инструмента'),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_ru',
            field=models.CharField(help_text='Например: Python, UI/UX Design, Docker, Figma', max_length=100, null=True, unique=True, verbose_name='Название технологии/инструмента'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category_ru', 'is_active'], name='services_se_categor_940283_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category_en', 'is_active'], name='services_se_categor_f5bb2c_idx'),
        ),
    ]
