# Generated by Django 5.2.9 on 2026-03-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_category_en_service_category_ru_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='service',
            new_name='srv_ord_act_idx',
            old_name='services_se_order_e13c4e_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='srv_pop_act_idx',
            old_name='services_se_is_popu_05a630_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='srv_cat_act_idx',
            old_name='services_se_categor_d8f4e5_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='srv_cat_act_idx-ru',
            old_name='services_se_categor_940283_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='srv_cat_act_idx-en',
            old_name='services_se_categor_f5bb2c_idx',
        ),
    ]
