# Generated by Django 5.2.9 on 2026-03-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_rename_services_se_order_e13c4e_idx_srv_ord_act_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='srv_cat_act_idx-ru',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='srv_cat_act_idx-en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='deliverables_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='deliverables_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='estimated_time_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='estimated_time_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name_ru',
        ),
    ]
