# Generated by Django 5.2.9 on 2026-03-15 22:27

import django.db.models.deletion
import main.utils
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    from django.utils.text import slugify

    for service in Service.objects.all():
        tag = service.old_category_tag
        if tag:
            category, created = ServiceCategory.objects.get_or_create(
                name=tag,
                defaults={'slug': slugify(tag) or 'category-' + str(service.id)}
            )
            service.category = category
            service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_portfolio_content_en_and_more'),
        ('services', '0012_remove_service_srv_cat_act_idx_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем.', max_length=200, verbose_name='Мета заголовок')),
                ('meta_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, verbose_name='Ключевые слова')),
                ('meta_description', models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, verbose_name='Мета описание')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL (slug)')),
                ('icon', models.FileField(blank=True, null=True, upload_to=main.utils.RenameUploadTo('services/categories/'), verbose_name='Иконка категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='old_category_tag',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='Категория'),
        ),
        migrations.RunPython(migrate_categories),
        migrations.AddField(
            model_name='service',
            name='related_portfolio',
            field=models.ManyToManyField(blank=True, help_text='Выберите работы, которые будут отображаться как примеры для этой услуги', related_name='related_services', to='portfolio.portfolio', verbose_name='Связанные работы из портфолио'),
        ),
        migrations.AlterField(
            model_name='service',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='Выберите стек технологий', related_name='services', to='services.technology', verbose_name='Стек технологий'),
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок преимущества')),
                ('description', models.TextField(blank=True, verbose_name='Описание преимущества')),
                ('icon_code', models.CharField(blank=True, help_text="Например: 'fas fa-rocket' или 'bi-check-circle'", max_length=100, verbose_name='Код иконки (FontAwesome/Bootstrap)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Преимущество услуги',
                'verbose_name_plural': 'Преимущества услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'FAQ услуги',
                'verbose_name_plural': 'FAQ услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена тарифа')),
                ('features_list', models.TextField(help_text='Каждая возможность с новой строки', verbose_name='Список возможностей')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемый тариф')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_plans', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='selected_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services.servicepriceplan', verbose_name='Выбранный тариф'),
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1, verbose_name='Номер этапа')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Что делаем на этом этапе')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
                'ordering': ['step_number', 'order'],
            },
        ),
    ]
