# Generated by Django 5.2.9 on 2026-03-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicecategory_service_old_category_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='old_category_tag',
            field=models.CharField(blank=True, help_text='Старое текстовое поле категории', max_length=100, verbose_name='Старый Тег (архив)'),
        ),
    ]
