# Generated by Django 5.2.9 on 2026-07-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_service_old_category_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepriceplan',
            name='is_available_for_order',
            field=models.BooleanField(default=True, help_text='Если отключено, этот тариф нельзя выбрать или заказать', verbose_name='Доступно для заказа'),
        ),
    ]
