# Generated by Django 5.2.9 on 2026-08-01

from django.db import migrations, models


def seed_default_features(apps, schema_editor):
    PricePlanFeature = apps.get_model('services', 'PricePlanFeature')
    default_items = [
        "Уникальный дизайн.",
        "Хостинг для сайта.",
        "Электронная почта.",
        "Система управления проектом.",
        "Обратная связь.",
        "Адаптивная верстка (Mobile/Desktop)",
        "Форма обратной связи",
        "Базовая SEO-оптимизация",
        "Срок: 20-30 дней",
    ]
    for idx, item_name in enumerate(default_items, start=1):
        PricePlanFeature.objects.get_or_create(
            name=item_name,
            defaults={'order': idx * 10}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicepriceplan_is_available_for_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Уникальный дизайн, Хостинг для сайта', max_length=255, unique=True, verbose_name='Название пункта/дополнения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Пункт тарифного плана',
                'verbose_name_plural': 'Пункты тарифных планов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='servicepriceplan',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Выберите пункты из списка или добавьте новые', related_name='price_plans', to='services.priceplanfeature', verbose_name='Выбранные пункты/дополнения'),
        ),
        migrations.AlterField(
            model_name='servicepriceplan',
            name='features_list',
            field=models.TextField(blank=True, help_text='Дополнительные текстовые пункты, каждая возможность с новой строки', verbose_name='Список возможностей (текстом)'),
        ),
        migrations.RunPython(seed_default_features, reverse_code=migrations.RunPython.noop),
    ]
