# Generated by Django 5.2.9 on 2026-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_priceplanfeature_servicepriceplan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Например: 'Пакет документов', 'Настроенная CRM'", max_length=255, verbose_name='Заголовок результата')),
                ('items_list', models.TextField(blank=True, help_text='Перечислите подпункты, каждый с новой строки.', verbose_name='Список подпунктов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Результат работы (Deliverable)',
                'verbose_name_plural': 'Результаты работы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='servicepriceplan',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Выберите пункты из списка или добавьте новые', related_name='price_plans', to='services.priceplanfeature', verbose_name='Пункты/дополнения'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_m2m',
            field=models.ManyToManyField(blank=True, help_text='Выберите готовые пункты с подпунктами для отображения в результатах работы', related_name='services', to='services.deliverable', verbose_name='Что вы получите в результате (пункты)'),
        ),
    ]
