# Generated by Django 5.2.9 on 2026-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_add_default_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestep',
            name='service',
        ),
        migrations.AddField(
            model_name='servicestep',
            name='price_plans',
            field=models.ManyToManyField(blank=True, related_name='steps', to='services.servicepriceplan', verbose_name='Тарифные планы, включающие шаг'),
        ),
        migrations.AddField(
            model_name='servicestep',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='steps', to='services.service', verbose_name='Услуги, которым принадлежит шаг'),
        ),
    ]
