# Generated by Django 5.2.9 on 2026-09-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_servicestep_service_servicestep_price_plans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='estimated_budget',
        ),
    ]
