# Generated by Django 5.2.9 on 2026-09-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_serviceorder_estimated_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='deadline',
        ),
    ]
