# Generated by Django 6.1 on 2026-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_remove_serviceorder_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Имя заказчика'),
        ),
    ]
