# Generated by Django 5.2.9 on 2026-01-02 12:26

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.RenameUploadTo('avatars/'), verbose_name='Аватар'),
        ),
    ]
