"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Используем переменные окружения для безопасности
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-tigran-quk)3wy#imok*1%@9f^5n63gh0=j&b66jw_3*(-awet65656fgdfgp4da_vi@2$l"  # fallback для разработки
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG должен быть False в production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

# ALLOWED_HOSTS = ["*"]
# Добавьте ваш домен/IP в ALLOWED_HOSTS
ALLOWED_HOSTS = [
    "*",
    "dpit-cms.ru",
    "213.171.7.204",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",  # Для sitemap.xml
    "captcha",  # Капча
    "main.apps.MainConfig",
    "news.apps.NewsConfig",
    'portfolio.apps.PortfolioConfig',
    "reviews.apps.ReviewsConfig",
    "logfiles.apps.LogfilesConfig",
    "accounts.apps.AccountsConfig",  # Регистрация и авторизация
    "tickets.apps.TicketsConfig",  # Система тикетов
    "tinymce",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.main_context",
                "news.context_processors.latest_news",
                "portfolio.context_processors.latest_portfolio",
                # "main.context_processors.latest_news",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Настройка модели пользователя
AUTH_USER_MODEL = "accounts.User"

# Настройки капчи
CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.random_char_challenge"
CAPTCHA_LENGTH = 5
CAPTCHA_TIMEOUT = 5
# Разрешите доступ к статическим файлам
SECURE_CONTENT_TYPE_NOSNIFF = False

# Jazzmin настройки
JAZZMIN_SETTINGS = {
    "site_title": "DPIT-CMS Admin",
    "site_header": "DPIT-CMS",
    "site_brand": "DPIT-CMS",
    "site_brand_small": "DPIT",
    "site_logo_classes": "img-circle",
    "site_logo": "images/logo.png",
    "site_footer": "DPIT-CMS",
    "menu_open_first_child": True,
    "welcome_sign": "Добро пожаловать в админ-панель DPIT-CMS",
    "copyright": "DPIT-CMS",
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "admin.logentry": "vertical_tabs",
    },
    # Дополнительные настройки UI
    "use_google_fonts_cdn": True,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["main", "news", "portfolio", "reviews", "accounts", "tickets"],
    "custom_links": {
        "main": [{
            "name": "Вернуться на сайт",
            "url": "/",
            "icon": "fas fa-home",
            "new_window": True,
        }]
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.SiteSettings": "fas fa-cog",
        "main.Page": "fas fa-file-alt",
        "news.NewsCategory": "fas fa-folder",
        "news.News": "fas fa-newspaper",
        "news.Comment": "fas fa-comments",
        "portfolio.PortfolioCategory": "fas fa-folder-open",
        "portfolio.Portfolio": "fas fa-images",
        "reviews.Review": "fas fa-star",
        "logfiles.LogFile": "fas fa-file-alt",
        "logfiles.LogBackup": "fas fa-archive",
        "accounts.User": "fas fa-user-circle",
        "tickets.Ticket": "fas fa-ticket-alt",
        "tickets.TicketMessage": "fas fa-comment-dots",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "css/admin_custom.css",
    "custom_js": None,
    "menu": [
        {
            "name": "Главная",
            "icon": "fas fa-home",
            "url": "/",
            "new_window": True,
        },
        {"app": "main", "icon": "fas fa-cogs"},
        {"app": "news", "icon": "fas fa-newspaper"},
        {"app": "portfolio", "icon": "fas fa-images"},
        {"app": "reviews", "icon": "fas fa-star"},
        {"app": "accounts", "icon": "fas fa-users"},
        {"app": "tickets", "icon": "fas fa-ticket-alt"},
        {"app": "logfiles", "icon": "fas fa-file-alt"},
    ],
}


# Настройки CSRF
CSRF_TRUSTED_ORIGINS = [
    "https://dpit-cms.ru",
    "http://dpit-cms.ru",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
# TinyMCE конфигурация
TINYMCE_DEFAULT_CONFIG = {
    "height": 360,
    "width": "100%",
    "cleanup_on_startup": True,
    "custom_undo_redo_levels": 20,
    "selector": "textarea",
    "plugins": "advlist autolink lists link image charmap print preview anchor",
    "toolbar": "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    "menubar": "edit view insert format tools table",
    "toolbar_mode": "floating",
    "content_css": "static/css/tinymce.css",
    "language": "ru",
    "file_picker_types": "image",
    "file_picker_callback": "customFilePicker",
}

# Если используете HTTPS (только в production)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"

# Настройки логирования
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "skip_broken_pipe": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: "Broken pipe" not in record.getMessage(),
        },
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "formatter": "verbose",
        },
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["skip_broken_pipe"],
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "news": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

# Кеширование
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
        "TIMEOUT": 300,  # 5 минут
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}

# Создаем директорию для логов, если её нет
logs_dir = BASE_DIR / "logs"
if not logs_dir.exists():
    os.makedirs(logs_dir, exist_ok=True)

# CSRF_COOKIE_DOMAIN = 'dpit-cms.ru'
# SESSION_COOKIE_DOMAIN = 'dpit-cms.ru'

# CSRF_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SAMESITE = 'None'
