# Generated by Django 4.2.7 on 2025-08-23 10:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Мета заголовок')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Мета описание')),
                ('content', tinymce.models.HTMLField(default='<p>Контент сайта</p>', verbose_name='Контент')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='Название сайта')),
                ('site_description', models.TextField(verbose_name='Описание сайта')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Мета описание')),
                ('content', tinymce.models.HTMLField(default='<p>Контент сайта</p>', verbose_name='Контент')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип')),
                ('favicon', models.ImageField(upload_to='favicons/', verbose_name='Фавикон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
