# Generated by Django 4.2.7 on 2025-09-06 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(200)], verbose_name='Мета заголовок')),
                ('meta_keywords', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Ключевые слова')),
                ('meta_description', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(255)], verbose_name='Мета описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('site_title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Название сайта')),
                ('site_description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание сайта')),
                ('content', tinymce.models.HTMLField(default='<p>Контент сайта</p>', verbose_name='Контент')),
                ('logo', models.ImageField(help_text='Рекомендуемый размер: 200x60px', upload_to='logos/', verbose_name='Логотип')),
                ('favicon', models.ImageField(help_text='Рекомендуемый размер: 32x32px', upload_to='favicons/', verbose_name='Фавикон')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(200)], verbose_name='Мета заголовок')),
                ('meta_keywords', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Ключевые слова')),
                ('meta_description', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(255)], verbose_name='Мета описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(help_text='URL страницы (например: about-us)', unique=True, verbose_name='URL')),
                ('content', tinymce.models.HTMLField(default='<p>Контент страницы</p>', verbose_name='Контент')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('template', models.CharField(default='main/page_detail.html', help_text='Путь к шаблону страницы', max_length=100, verbose_name='Шаблон')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.page', verbose_name='Родительская страница')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'title'],
                'unique_together': {('slug', 'parent')},
            },
        ),
    ]
