# Generated by Django 4.2.7 on 2025-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_slogan',
            field=models.CharField(default=' ', max_length=10, verbose_name='Слоган'),
            preserve_default=False,
        ),
    ]
