# Generated by Django 4.2.7 on 2025-08-23 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contents',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Контент'),
            preserve_default=False,
        ),
    ]
