# Generated by Django 4.2.7 on 2025-09-06 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.page', verbose_name='Родительская страница'),
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(default='main/page_detail.html', help_text='Путь к шаблону страницы', max_length=100, verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=' ', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default=1, max_length=200, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(200)], verbose_name='Мета заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(default='<p>Контент страницы</p>', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(255)], verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(200)], verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='URL страницы (например: about-us)', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(help_text='Рекомендуемый размер: 32x32px', upload_to='favicons/', verbose_name='Фавикон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(help_text='Рекомендуемый размер: 200x60px', upload_to='logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(255)], verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Название сайта'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('slug', 'parent')},
        ),
    ]
