# Generated by Django 5.2.9 on 2025-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesettings_site_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_email',
            field=models.EmailField(default=' ', max_length=20, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_phone_1',
            field=models.CharField(default=' ', max_length=11, verbose_name='Телефон 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_phone_2',
            field=models.CharField(default=' ', max_length=11, verbose_name='Телефон 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_slogan',
            field=models.CharField(max_length=30, verbose_name='Слоган'),
        ),
    ]
