# Generated by Django 4.2.7 on 2025-08-23 08:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesettings_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contents',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='content',
            field=tinymce.models.HTMLField(default=2, verbose_name='Содержание'),
            preserve_default=False,
        ),
    ]
