# Generated by Django 5.2.9 on 2025-12-29 13:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesettings_site_email_sitesettings_site_phone_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип, ассоциированный с данной страницей. Отображается в шапке или футере.', null=True, upload_to='page_logos/', verbose_name='Логотип страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', help_text='Основной контент страницы с поддержкой HTML-разметки.', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если снята галочка, страница будет скрыта с сайта.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(help_text='Краткое описание страницы для поисковых систем.', max_length=255, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(help_text='Список ключевых слов через запятую для SEO.', max_length=200, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(help_text='Заголовок страницы для поисковых систем и социальных сетей.', max_length=200, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, help_text='Определяет порядок сортировки страниц в меню и списке.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Определите, будет ли страница отображаться в основном меню сайта.', verbose_name='Показывать в меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text="Уникальный идентификатор страницы в URL (например, 'about-us').", unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Введите заголовок страницы, отображаемый в браузере и на сайте.', max_length=200, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
