# Generated by Django 4.2.7 on 2025-08-23 09:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sitesettings_contents_sitesettings_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='content',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', verbose_name='Контент'),
        ),
    ]
