# Generated by Django 5.2.9 on 2025-12-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_page_logo_alter_page_content_alter_page_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='fon_headers',
            field=models.ImageField(blank=True, help_text='Фон, ассоциированный с данной страницей. Отображается в шапке или футере.', null=True, upload_to='fon_headers/', verbose_name='Фон шапки страницы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fon_haeders',
            field=models.ImageField(default=' ', upload_to='fon_haeders/', verbose_name='Фон шапки'),
            preserve_default=False,
        ),
    ]
