# Generated by Django 5.2.9 on 2025-12-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_page_fon_headers_sitesettings_fon_haeders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_domain',
            field=models.CharField(blank=True, help_text='Домен сайта для отображения в шапке (например, dpit-cms.ru). Если не указан, будет использоваться текущий хост.', max_length=200, null=True, verbose_name='Домен сайта'),
        ),
    ]
