# Generated by Django 5.2.9 on 2026-01-02 12:26

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesettings_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='fon_headers',
            field=models.ImageField(blank=True, help_text='Фон, ассоциированный с данной страницей. Отображается в шапке или футере.', null=True, upload_to=main.utils.RenameUploadTo('fon_headers/'), verbose_name='Фон шапки страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип, ассоциированный с данной страницей. Отображается в шапке или футере.', null=True, upload_to=main.utils.RenameUploadTo('page_logos/'), verbose_name='Логотип страницы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(upload_to=main.utils.RenameUploadTo('favicons/'), verbose_name='Фавикон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='fon_haeders',
            field=models.ImageField(upload_to=main.utils.RenameUploadTo('fon_haeders/'), verbose_name='Фон шапки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(upload_to=main.utils.RenameUploadTo('logos/'), verbose_name='Логотип'),
        ),
    ]
