# Generated by Django 5.2.9 on 2026-01-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_page_fon_headers_alter_page_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем.', max_length=200, verbose_name='Мета заголовок'),
        ),
    ]
