# Generated by Django 5.2.9 on 2026-01-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_page_is_active_alter_page_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем.', max_length=200, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, verbose_name='Ключевые слова'),
        ),
    ]
