# Generated by Django 5.2.9 on 2026-01-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sitesettings_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_address',
            field=models.CharField(default=' ', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
