# Generated by Django 5.2.9 on 2026-01-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sitesettings_site_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_work_time',
            field=models.CharField(blank=True, help_text='Время работы компании (например: Пн-Пт: 9:00-18:00)', max_length=100, null=True, verbose_name='Время работы'),
        ),
    ]
