# Generated by Django 5.2.9 on 2026-01-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sitesettings_site_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(max_length=255, verbose_name='Описание сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_email',
            field=models.EmailField(max_length=30, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_phone_1',
            field=models.CharField(max_length=20, verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_phone_2',
            field=models.CharField(max_length=20, verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_work_time',
            field=models.CharField(blank=True, help_text='Время работы компании (например: Пн-Пт: 9:00-18:00)', max_length=200, null=True, verbose_name='Время работы'),
        ),
    ]
