# Generated by Django 5.2.9 on 2026-01-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_sitesettings_site_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_ss_vk',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть ВК', max_length=200, verbose_name='Социальная сеть VK'),
        ),
    ]
