# Generated by Django 5.2.9 on 2026-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitesettings_site_ss_vk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_ss_ok',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть OK', max_length=200, verbose_name='Социальная сеть OK'),
        ),
    ]
