# Generated by Django 5.2.9 on 2026-01-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sitesettings_site_ss_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_ss_fb',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть FaceBook', max_length=200, verbose_name='Социальная сеть FB'),
        ),
    ]
