# Generated by Django 5.2.9 on 2026-01-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sitesettings_site_ss_fb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_ss_fb',
            new_name='site_fb',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_ss_ok',
            new_name='site_ok',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_ss_vk',
            new_name='site_vk',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_instagram',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть instagram', max_length=200, verbose_name='Социальная сеть instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_linkedin',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть linkedin', max_length=200, verbose_name='Социальная сеть linkedin'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_telegram',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть telegram', max_length=200, verbose_name='Социальная сеть telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_twitter',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть twitter', max_length=200, verbose_name='Социальная сеть twitter'),
        ),
    ]
