# Generated by Django 5.2.9 on 2026-01-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_site_ss_fb_sitesettings_site_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_whatsapp',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть whatsapp', max_length=200, verbose_name='Социальная сеть whatsapp'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_youtube',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть youtube', max_length=200, verbose_name='Социальная сеть youtube'),
        ),
    ]
