# Generated by Django 5.2.9 on 2026-01-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sitesettings_site_whatsapp_sitesettings_site_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_fb',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_facebook',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть FaceBook', max_length=200, verbose_name='FaceBook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_instagram',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть instagram', max_length=200, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_linkedin',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть linkedin', max_length=200, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_ok',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть OK', max_length=200, verbose_name='OK'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_telegram',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть telegram', max_length=200, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_twitter',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть twitter', max_length=200, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_vk',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть ВК', max_length=200, verbose_name='VK'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_whatsapp',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть whatsapp', max_length=200, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_youtube',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть youtube', max_length=200, verbose_name='Youtube'),
        ),
    ]
