# Generated by Django 5.2.9 on 2026-01-06 18:17

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_sitesettings_site_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_vk_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети ВКонтакте', max_length=200, null=True, upload_to=main.utils.RenameUploadTo('images/ss-icons/'), verbose_name='VK-Иконка'),
        ),
    ]
