# Generated by Django 5.2.9 on 2026-01-06 18:24

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitesettings_site_vk_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_facebook_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети Facebook', null=True, upload_to=main.utils.RenameUploadTo('social/facebook/'), verbose_name='FaceBook иконка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_instagram_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети Instagram', null=True, upload_to=main.utils.RenameUploadTo('social/instagram/'), verbose_name='Instagram иконка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_linkedin_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети LinkedIn', null=True, upload_to=main.utils.RenameUploadTo('social/linkedin/'), verbose_name='Linkedin иконка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_ok_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети Одноклассники', null=True, upload_to=main.utils.RenameUploadTo('social/ok/'), verbose_name='OK иконка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_telegram_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети Telegram', null=True, upload_to=main.utils.RenameUploadTo('social/telegram/'), verbose_name='Telegram иконка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_twitter_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети Twitter', null=True, upload_to=main.utils.RenameUploadTo('social/twitter/'), verbose_name='Twitter иконка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_whatsapp_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети WhatsApp', null=True, upload_to=main.utils.RenameUploadTo('social/whatsapp/'), verbose_name='Whatsapp иконка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_youtube_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети YouTube', null=True, upload_to=main.utils.RenameUploadTo('social/youtube/'), verbose_name='Youtube иконка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_instagram',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть Instagram', max_length=200, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_linkedin',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть Linkedin', max_length=200, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_telegram',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть Telegram', max_length=200, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_twitter',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть Twitter', max_length=200, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_vk_img',
            field=models.ImageField(blank=True, help_text='Изображение иконки для социальной сети ВКонтакте', null=True, upload_to=main.utils.RenameUploadTo('social/vk/'), verbose_name='VK иконка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_whatsapp',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть Whatsapp', max_length=200, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_youtube',
            field=models.CharField(blank=True, help_text='Ссылка на социальную сеть Youtube', max_length=200, verbose_name='Youtube'),
        ),
    ]
