# Generated by Django 5.2.9 on 2026-01-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_sitesettings_site_facebook_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('name', models.CharField(help_text='Например: Яндекс.Метрика', max_length=100, verbose_name='Название скрипта')),
                ('script_code', models.TextField(help_text='Вставьте полный код счетчика или скрипта', verbose_name='HTML/JS код')),
                ('position', models.IntegerField(default=0, help_text='Чем меньше число, тем раньше выводится скрипт', verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Скрипт аналитики',
                'verbose_name_plural': 'Скрипты аналитики',
                'ordering': ['position', 'name'],
            },
        ),
    ]
