# Generated by Django 5.2.9 on 2026-03-09 23:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_analyticsscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', help_text='Основной контент страницы с поддержкой HTML-разметки.', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', help_text='Основной контент страницы с поддержкой HTML-разметки.', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(help_text='Введите заголовок страницы, отображаемый в браузере и на сайте.', max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(help_text='Введите заголовок страницы, отображаемый в браузере и на сайте.', max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='content_en',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='content_ru',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем.', max_length=255, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую.', max_length=200, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем.', max_length=200, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='Заголовок страницы для поисковых систем.', max_length=200, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_slogan_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_slogan_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название сайта'),
        ),
    ]
