# Generated by Django 5.2.9 on 2026-03-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_page_content_en_page_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_description_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_keywords_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_title_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_description_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_description_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_slogan_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_slogan_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_title_ru',
        ),
    ]
