# Generated by Django 5.2.9 on 2026-08-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_page_content_en_remove_page_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='description_of_services_block',
            field=models.TextField(blank=True, default='Профессиональные цифровые решения для роста и масштабирования вашего бизнеса.', verbose_name='Описание блока услуг'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_block_title',
            field=models.CharField(blank=True, default='Наши услуги', max_length=200, verbose_name='Заголовок блока услуг'),
        ),
    ]
