# Generated by Django 5.2.9 on 2025-12-30 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя файла лога', max_length=255, verbose_name='Название файла')),
                ('file_path', models.CharField(help_text='Полный путь к файлу лога', max_length=500, verbose_name='Путь к файлу')),
                ('size', models.BigIntegerField(default=0, help_text='Размер файла в байтах', verbose_name='Размер (байт)')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения файла', verbose_name='Последнее изменение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'Файл лога',
                'verbose_name_plural': 'Файлы логов',
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='LogBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.FileField(help_text='Файл резервной копии', upload_to='logs/backups/', verbose_name='Резервная копия')),
                ('backup_size', models.BigIntegerField(default=0, verbose_name='Размер копии (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания копии')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание резервной копии', null=True, verbose_name='Описание')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='logfiles.logfile', verbose_name='Файл лога')),
            ],
            options={
                'verbose_name': 'Резервная копия лога',
                'verbose_name_plural': 'Резервные копии логов',
                'ordering': ['-created_at'],
            },
        ),
    ]
