# Generated by Django 5.2.9 on 2026-01-02 14:33

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbackup',
            name='backup_file',
            field=models.FileField(help_text='Файл резервной копии', upload_to=main.utils.RenameUploadTo('logs/backups/'), verbose_name='Резервная копия'),
        ),
    ]
