# Generated by Django 4.2.7 on 2025-08-26 22:09

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('logo', models.ImageField(upload_to='portfolio/categories/', verbose_name='Логотип')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Мета заголовок')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('description', models.TextField(verbose_name='Описание')),
                ('content', tinymce.models.HTMLField(default='<p>Описание</p>', verbose_name='Описание на странице')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория портфолио',
                'verbose_name_plural': 'Категории портфолио',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='Изображение')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Мета заголовок')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Мета описание')),
                ('content', tinymce.models.HTMLField(default='<p>Контент сайта</p>', verbose_name='Контент')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfoliocategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфель',
                'ordering': ['-created_at'],
            },
        ),
    ]
