# Generated by Django 5.2.9 on 2026-01-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='header_description',
            field=models.TextField(blank=True, help_text='Оставьте пустым, чтобы использовать описание категории.', null=True, verbose_name='Описание шапки'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Оставьте пустым, чтобы использовать изображение по умолчанию из настроек сайта.', null=True, upload_to='portfolio/headers/', verbose_name='Изображение шапки'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='header_title',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать название категории.', max_length=200, null=True, verbose_name='Заголовок шапки'),
        ),
    ]
