# Generated by Django 5.2.9 on 2026-01-02 12:26

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliocategory_header_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to=main.utils.RenameUploadTo('portfolio/images/'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Оставьте пустым, чтобы использовать изображение по умолчанию из настроек сайта.', null=True, upload_to=main.utils.RenameUploadTo('portfolio/headers/'), verbose_name='Изображение шапки'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='logo',
            field=models.ImageField(upload_to=main.utils.RenameUploadTo('portfolio/categories/'), verbose_name='Логотип'),
        ),
    ]
