# Generated by Django 5.2.9 on 2026-01-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Портфолио/Услуга', 'verbose_name_plural': 'Портфолио/Услуги'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Это услуга'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('service', models.ForeignKey(limit_choices_to={'is_service': True}, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ услуги',
                'verbose_name_plural': 'Заказы услуг',
                'ordering': ['-created_at'],
            },
        ),
    ]
