# Generated by Django 5.2.9 on 2026-01-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolio_options_portfolio_is_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (максимальная)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (минимальная)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (обычная)'),
        ),
    ]
