# Generated by Django 5.2.9 on 2026-01-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_max_price_portfolio_min_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='is_service',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='price',
        ),
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
    ]
