# Generated by Django 5.2.9 on 2026-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfolio_options_remove_portfolio_is_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_available_for_order',
            field=models.BooleanField(default=False, verbose_name='Доступно для заказа'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (Оформление)'),
        ),
    ]
