# Generated by Django 5.2.9 on 2026-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_portfolio_is_available_for_order_portfolio_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Конечная цена (ДО)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Начальная цена (ОТ)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('range', 'От и До'), ('contact', 'По договоренности')], default='fixed', max_length=10, verbose_name='Тип ценообразования'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (Фикс)'),
        ),
    ]
