# Generated by Django 5.2.9 on 2026-03-09 23:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolio_price_max_portfolio_price_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='content_en',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content_ru',
            field=tinymce.models.HTMLField(default='<p>Контент сайта</p>', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='content_en',
            field=tinymce.models.HTMLField(default='<p>Описание</p>', null=True, verbose_name='Описание на странице'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='content_ru',
            field=tinymce.models.HTMLField(default='<p>Описание</p>', null=True, verbose_name='Описание на странице'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
