# Generated by Django 5.2.9 on 2026-03-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolio_content_en_portfolio_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='name_ru',
        ),
    ]
