# Generated by Django 5.2.9 on 2026-02-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('portfolio', '0008_portfolio_is_available_for_order_portfolio_price'),
        ('services', '0008_technology_alter_serviceorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='portfolio.portfolio', verbose_name='Работа (Портфолио)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='services.service', verbose_name='Услуга'),
        ),
    ]
