# Generated by Django 5.2.9 on 2026-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_portfolio_alter_orderitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Конечная цена'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Начальная цена'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_type',
            field=models.CharField(default='fixed', max_length=10, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (фикс)'),
        ),
    ]
