# Generated by Django 5.2.9 on 2026-03-14 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem_price_max_orderitem_price_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Латинские буквы, цифры. Например: SUMMER2025', max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент (%)'), ('fixed', 'Фиксированная сумма (₽)')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Для процентов — значение 1–100, для фиксированной суммы — в рублях', max_digits=10, verbose_name='Размер скидки')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действителен с')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Оставьте пустым для бессрочного промокода', null=True, verbose_name='Действителен до')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 — безлимитно', verbose_name='Макс. кол-во активаций')),
                ('current_uses', models.PositiveIntegerField(default=0, editable=False, verbose_name='Текущее кол-во активаций')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма скидки')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usage', to='cart.order', verbose_name='Заказ')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='cart.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'История промокодов',
            },
        ),
    ]
