# Generated by Django 5.2.9 on 2026-03-20 20:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_promocode_promocodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_registered',
            field=models.BooleanField(default=False, help_text='Клиент был автоматически зарегистрирован при оформлении заказа', verbose_name='Авторегистрация'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_applied',
            field=models.CharField(blank=True, max_length=50, verbose_name='Применённый промокод'),
        ),
    ]
