# Generated by Django 6.1 on 2026-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_add_order_discount_fields'),
        ('services', '0023_alter_serviceorder_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_plans',
            field=models.ManyToManyField(blank=True, to='services.servicepriceplan', verbose_name='Выбранные тарифные планы для переговоров'),
        ),
    ]
